{% set name = "spaces" %}
{% set version = "1.0.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_rev: "{{ version }}"
  git_url: "git@github.com:ubcdsci/spaces.git"

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - grasp-analytics

about:
  home: https://github.com/ubcdsci/spaces
  license: BSD
  license_family: BSD
  summary: Spaces project
